### ISSUE TITLE
Why do you include the autoloader in the config paths file?

### ISSUE THREAD

**Issue by exts** [opulencephp/Project#11]
In [this file](https://github.com/opulencephp/Project/blob/1.1/config/paths.php) you directly call the autoloader.

What if you wanted to parse that config somewhere else? In a bridge project for instance (where you're connecting say a forum & your custom site together) and you needed some settings from that file? It would automatically call the autoloader. Seems like this was a temporary solution that needs to be moved elsewhere imho.

**Comment by davidbyoung** [comment]
Fair point.  I've changed this as of v1.1.1.
