### ISSUE TITLE
.gitignore missing from new projects

### ISSUE THREAD

**Issue by itised** [opulencephp/Project#3]
The recommended install method (composer create-project) ignores the .gitignore file, but the .gitignore file is pretty standard stuff. I'm assuming it's left out because people may not use git and therefore wouldn't need it?

I would think it's easier for the fewer people who don't need it to delete it than for the majority of people who will need it to add it back in. It's not a huge hassle, but I personally have found myself copying and pasting it a few times now.

**Comment by davidbyoung** [comment]
The alternative is write an installation script that doesn't use composer create-project.  While I'm certainly not opposed to that, it'd take some work to implement such a script that would work across platforms.  I've added this feature to the [todo list](https://github.com/opulencephp/Project/wiki/Todo).

**Comment by itised** [comment]
I was under the impression that just removing the line ".gitignore export-ignore" from the .gitattributes file would fix it. But to be honest I haven't actually tried it.

**Comment by davidbyoung** [comment]
Hmm, you might actually be correct.  I'll try it out later this weekend and let you know.

**Comment by davidbyoung** [comment]
Done
